// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Code string `json:"code" valid:"code"`
}

type LoginResp struct {
	UserID    string `json:"user_id"`
	OpenID    string `json:"openid"`
	UnionID   string `json:"unionid"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Phone     string `json:"phone"`
	IsDisable int32  `json:"is_disable"`
	Token     string `json:"token"` // JWT token
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type TagListReq struct {
	Type string `json:"type,optional" valid:"type"` // expense-支出 income-收入
}

type TagListResp struct {
	TagId    int64  `json:"tag_id"`
	UserId   string `json:"user_id"` // 0-系统标签 非0-用户自定义标签
	Name     string `json:"name"`
	Color    string `json:"color"`
	Icon     string `json:"icon"`
	IsSystem int64  `json:"is_system"` // 1-系统标签 2-用户自定义标签
	Type     string `json:"type"`      // expense-支出 income-收入
	SortNum  int64  `json:"sort_num"`  // 排序序号
}

type UpdateUserSettingsReq struct {
	BackgroundUrl string  `json:"background_url,optional" valid:"background_url"`
	Budget        float64 `json:"budget,optional" valid:"budget"`
}

type UpdateUserSettingsResp struct {
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserId    string `json:"user_id"`
	OpenId    string `json:"openid"`
	UnionId   string `json:"unionid"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Phone     string `json:"phone"`
	IsDisable int    `json:"is_disable"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UserLogoutReq struct {
}

type UserLogoutResp struct {
}

type UserSettingsReq struct {
}

type UserSettingsResp struct {
	UserSettingID int64   `json:"user_setting_id"`
	UserId        string  `json:"user_id"`
	BackgroundUrl string  `json:"background_url"`
	Budget        float64 `json:"budget"`
	CreatedAt     int64   `json:"created_at"`
	UpdatedAt     int64   `json:"updated_at"`
}

type UserUpdateReq struct {
	Nickname string `json:"nickname,optional" valid:"code"`
	Avatar   string `json:"avatar,optional" valid:"avatar"`
	Phone    string `json:"phone,optional" valid:"phone"`
}

type UserUpdateResp struct {
	UserId    string `json:"user_id"`
	OpenId    string `json:"openid"`
	UnionId   string `json:"unionid"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Phone     string `json:"phone"`
	IsDisable int    `json:"is_disable"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}
