// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Code string `json:"code,optional"`
}

type LoginResp struct {
	UserID    string `json:"user_id"`
	OpenID    string `json:"openid"`
	UnionID   string `json:"unionid"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Phone     string `json:"phone"`
	IsDisable int32  `json:"is_disable"`
	Token     string `json:"token"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}
