// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/Masterminds/squirrel"
	"github.com/pudongping/momento-api/coreKit/paginator"
)

var (
	accountBookInvitationsFieldNames          = builder.RawFieldNames(&AccountBookInvitations{})
	accountBookInvitationsRows                = strings.Join(accountBookInvitationsFieldNames, ",")
	accountBookInvitationsRowsExpectAutoSet   = strings.Join(stringx.Remove(accountBookInvitationsFieldNames, "`invitation_id`"), ",")
	accountBookInvitationsRowsWithPlaceHolder = strings.Join(stringx.Remove(accountBookInvitationsFieldNames, "`invitation_id`"), "=?,") + "=?"
)

type (
	accountBookInvitationsModel interface {
		Insert(ctx context.Context, data *AccountBookInvitations) (sql.Result, error)

		// 自定义模版中扩展的方法 start ----->
		GetTableName() string
		Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error)
		InsertWithSession(ctx context.Context, session sqlx.Session, insertData map[string]interface{}) (sql.Result, error)
		DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error)
		UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error)
		SelectBuilder(fields ...string) squirrel.SelectBuilder
		CountBuilder(field ...string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error)
		FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error
		FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*AccountBookInvitations, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*AccountBookInvitations, error)
		FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*AccountBookInvitations, *paginator.Pagination, error)
		// 自定义模版中扩展的方法 end ---->
		FindOne(ctx context.Context, invitationId uint64) (*AccountBookInvitations, error)
		Update(ctx context.Context, data *AccountBookInvitations) error
		Delete(ctx context.Context, invitationId uint64) error
	}

	defaultAccountBookInvitationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AccountBookInvitations struct {
		InvitationId uint64 `db:"invitation_id"` // 邀请ID
		BookId       uint64 `db:"book_id"`       // 账本ID
		InviterUid   uint64 `db:"inviter_uid"`   // 邀请人UID
		TargetUid    uint64 `db:"target_uid"`    // 被邀请人UID
		Status       string `db:"status"`        // 邀请状态
		CreatedAt    uint64 `db:"created_at"`    // 创建时间（秒级时间戳）
		UpdatedAt    uint64 `db:"updated_at"`    // 更新时间（秒级时间戳）
	}
)

func newAccountBookInvitationsModel(conn sqlx.SqlConn) *defaultAccountBookInvitationsModel {
	return &defaultAccountBookInvitationsModel{
		conn:  conn,
		table: "`account_book_invitations`",
	}
}

func (m *defaultAccountBookInvitationsModel) Delete(ctx context.Context, invitationId uint64) error {
	query := fmt.Sprintf("delete from %s where `invitation_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, invitationId)
	return err
}

func (m *defaultAccountBookInvitationsModel) FindOne(ctx context.Context, invitationId uint64) (*AccountBookInvitations, error) {
	query := fmt.Sprintf("select %s from %s where `invitation_id` = ? limit 1", accountBookInvitationsRows, m.table)
	var resp AccountBookInvitations
	err := m.conn.QueryRowCtx(ctx, &resp, query, invitationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountBookInvitationsModel) Insert(ctx context.Context, data *AccountBookInvitations) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, accountBookInvitationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BookId, data.InviterUid, data.TargetUid, data.Status, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

// 自定义模版中扩展的方法 start ----->

func (m *defaultAccountBookInvitationsModel) GetTableName() string {
	return m.tableName()
}

func (m *defaultAccountBookInvitationsModel) Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultAccountBookInvitationsModel) ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error) {
	if session != nil {
		return session.ExecCtx(ctx, query, args...)
	}
	return m.conn.ExecCtx(ctx, query, args...)
}

func (m *defaultAccountBookInvitationsModel) InsertWithSession(ctx context.Context, session sqlx.Session, insertData map[string]interface{}) (sql.Result, error) {
	insertBuilder := squirrel.Insert(m.table).SetMap(insertData)
	query, values, err := insertBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultAccountBookInvitationsModel) DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error) {
	deleteBuilder := squirrel.Delete(m.table).Where(where)
	query, values, err := deleteBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultAccountBookInvitationsModel) UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error) {
	updateBuilder := squirrel.Update(m.table).SetMap(updateData).Where(where)
	query, values, err := updateBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultAccountBookInvitationsModel) SelectBuilder(fields ...string) squirrel.SelectBuilder {
	f := accountBookInvitationsRows
	if len(fields) > 0 {
		f = strings.Join(fields, ",")
	}
	return squirrel.Select(f).From(m.table)
}

func (m *defaultAccountBookInvitationsModel) CountBuilder(field ...string) squirrel.SelectBuilder {
	f := "*"
	if len(field) > 0 && field[0] != "" {
		f = field[0]
	}
	return squirrel.Select("COUNT(" + f + ")").From(m.table)
}

func (m *defaultAccountBookInvitationsModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultAccountBookInvitationsModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {
	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultAccountBookInvitationsModel) FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error) {
	query, values, err := sumBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultAccountBookInvitationsModel) FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return err
	}

	return m.conn.QueryRowsCtx(ctx, bindings, query, values...)

}

func (m *defaultAccountBookInvitationsModel) FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*AccountBookInvitations, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp AccountBookInvitations

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}

}

func (m *defaultAccountBookInvitationsModel) FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*AccountBookInvitations, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*AccountBookInvitations

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultAccountBookInvitationsModel) FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*AccountBookInvitations, *paginator.Pagination, error) {
	// 构建查询数据总条数的 sql 语句
	countQuery, countValues, err := paginator.CountDataSqlBuilder(rowBuilder).ToSql()
	if err != nil {
		return nil, nil, err
	}

	var total int64

	err = m.conn.QueryRowCtx(ctx, &total, countQuery, countValues...)

	if err != nil {
		return nil, nil, err
	}

	currentPage, limit, offset := paginator.PrepareOffsetLimit(page, perPage)
	pagination := paginator.NewPagination(total, currentPage, limit)

	builder := rowBuilder.Offset(uint64(offset)).Limit(uint64(limit))
	builder = paginator.WithOrderBy(orderBy, builder)

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, nil, err
	}

	var resp []*AccountBookInvitations

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, pagination, nil
	default:
		return nil, nil, err
	}
}

// 自定义模版中扩展的方法 end ---->

func (m *defaultAccountBookInvitationsModel) Update(ctx context.Context, data *AccountBookInvitations) error {
	query := fmt.Sprintf("update %s set %s where `invitation_id` = ?", m.table, accountBookInvitationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BookId, data.InviterUid, data.TargetUid, data.Status, data.CreatedAt, data.UpdatedAt, data.InvitationId)
	return err
}

func (m *defaultAccountBookInvitationsModel) tableName() string {
	return m.table
}
