// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/Masterminds/squirrel"
	"github.com/pudongping/momento-api/coreKit/paginator"
)

var (
	accountBookMembersFieldNames          = builder.RawFieldNames(&AccountBookMembers{})
	accountBookMembersRows                = strings.Join(accountBookMembersFieldNames, ",")
	accountBookMembersRowsExpectAutoSet   = strings.Join(stringx.Remove(accountBookMembersFieldNames, "`book_member_id`"), ",")
	accountBookMembersRowsWithPlaceHolder = strings.Join(stringx.Remove(accountBookMembersFieldNames, "`book_member_id`"), "=?,") + "=?"
)

type (
	accountBookMembersModel interface {
		Insert(ctx context.Context, data *AccountBookMembers) (sql.Result, error)

		// 自定义模版中扩展的方法 start ----->
		GetTableName() string
		Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error)
		DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error)
		UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error)
		SelectBuilder(fields ...string) squirrel.SelectBuilder
		CountBuilder(field ...string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error)
		FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error
		FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*AccountBookMembers, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*AccountBookMembers, error)
		FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*AccountBookMembers, *paginator.Pagination, error)
		// 自定义模版中扩展的方法 end ---->
		FindOne(ctx context.Context, bookMemberId uint64) (*AccountBookMembers, error)
		FindOneByBookIdUserId(ctx context.Context, bookId uint64, userId uint64) (*AccountBookMembers, error)
		Update(ctx context.Context, data *AccountBookMembers) error
		Delete(ctx context.Context, bookMemberId uint64) error
	}

	defaultAccountBookMembersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AccountBookMembers struct {
		BookMemberId uint64 `db:"book_member_id"` // 账本成员ID
		BookId       uint64 `db:"book_id"`        // 账本ID
		UserId       uint64 `db:"user_id"`        // 用户ID
		IsCreator    int64  `db:"is_creator"`     // 是否为创建者 1-是 2-否
		IsDefault    int64  `db:"is_default"`     // 是否为默认账本 1-是 2-否
		Status       string `db:"status"`         // 成员状态
		JoinedAt     uint64 `db:"joined_at"`      // 加入时间（秒级时间戳）
		CreatedAt    uint64 `db:"created_at"`     // 创建时间（秒级时间戳）
		UpdatedAt    uint64 `db:"updated_at"`     // 更新时间（秒级时间戳）
	}
)

func newAccountBookMembersModel(conn sqlx.SqlConn) *defaultAccountBookMembersModel {
	return &defaultAccountBookMembersModel{
		conn:  conn,
		table: "`account_book_members`",
	}
}

func (m *defaultAccountBookMembersModel) Delete(ctx context.Context, bookMemberId uint64) error {
	query := fmt.Sprintf("delete from %s where `book_member_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, bookMemberId)
	return err
}

func (m *defaultAccountBookMembersModel) FindOne(ctx context.Context, bookMemberId uint64) (*AccountBookMembers, error) {
	query := fmt.Sprintf("select %s from %s where `book_member_id` = ? limit 1", accountBookMembersRows, m.table)
	var resp AccountBookMembers
	err := m.conn.QueryRowCtx(ctx, &resp, query, bookMemberId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountBookMembersModel) FindOneByBookIdUserId(ctx context.Context, bookId uint64, userId uint64) (*AccountBookMembers, error) {
	var resp AccountBookMembers
	query := fmt.Sprintf("select %s from %s where `book_id` = ? and `user_id` = ? limit 1", accountBookMembersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, bookId, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountBookMembersModel) Insert(ctx context.Context, data *AccountBookMembers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, accountBookMembersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BookId, data.UserId, data.IsCreator, data.IsDefault, data.Status, data.JoinedAt, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

// 自定义模版中扩展的方法 start ----->

func (m *defaultAccountBookMembersModel) GetTableName() string {
	return m.tableName()
}

func (m *defaultAccountBookMembersModel) Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultAccountBookMembersModel) ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error) {
	if session != nil {
		return session.ExecCtx(ctx, query, args...)
	}
	return m.conn.ExecCtx(ctx, query, args...)
}

func (m *defaultAccountBookMembersModel) DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error) {
	deleteBuilder := squirrel.Delete(m.table).Where(where)
	query, values, err := deleteBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultAccountBookMembersModel) UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error) {
	updateBuilder := squirrel.Update(m.table).SetMap(updateData).Where(where)
	query, values, err := updateBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultAccountBookMembersModel) SelectBuilder(fields ...string) squirrel.SelectBuilder {
	f := accountBookMembersRows
	if len(fields) > 0 {
		f = strings.Join(fields, ",")
	}
	return squirrel.Select(f).From(m.table)
}

func (m *defaultAccountBookMembersModel) CountBuilder(field ...string) squirrel.SelectBuilder {
	f := "*"
	if len(field) > 0 && field[0] != "" {
		f = field[0]
	}
	return squirrel.Select("COUNT(" + f + ")").From(m.table)
}

func (m *defaultAccountBookMembersModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultAccountBookMembersModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {
	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultAccountBookMembersModel) FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error) {
	query, values, err := sumBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultAccountBookMembersModel) FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return err
	}

	return m.conn.QueryRowsCtx(ctx, bindings, query, values...)

}

func (m *defaultAccountBookMembersModel) FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*AccountBookMembers, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp AccountBookMembers

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}

}

func (m *defaultAccountBookMembersModel) FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*AccountBookMembers, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*AccountBookMembers

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultAccountBookMembersModel) FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*AccountBookMembers, *paginator.Pagination, error) {
	// 构建查询数据总条数的 sql 语句
	countQuery, countValues, err := paginator.CountDataSqlBuilder(rowBuilder).ToSql()
	if err != nil {
		return nil, nil, err
	}

	var total int64

	err = m.conn.QueryRowCtx(ctx, &total, countQuery, countValues...)

	if err != nil {
		return nil, nil, err
	}

	currentPage, limit, offset := paginator.PrepareOffsetLimit(page, perPage)
	pagination := paginator.NewPagination(total, currentPage, limit)

	builder := rowBuilder.Offset(uint64(offset)).Limit(uint64(limit))
	builder = paginator.WithOrderBy(orderBy, builder)

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, nil, err
	}

	var resp []*AccountBookMembers

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, pagination, nil
	default:
		return nil, nil, err
	}
}

// 自定义模版中扩展的方法 end ---->

func (m *defaultAccountBookMembersModel) Update(ctx context.Context, newData *AccountBookMembers) error {
	query := fmt.Sprintf("update %s set %s where `book_member_id` = ?", m.table, accountBookMembersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.BookId, newData.UserId, newData.IsCreator, newData.IsDefault, newData.Status, newData.JoinedAt, newData.CreatedAt, newData.UpdatedAt, newData.BookMemberId)
	return err
}

func (m *defaultAccountBookMembersModel) tableName() string {
	return m.table
}
