// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/Masterminds/squirrel"
	"github.com/pudongping/momento-api/coreKit/paginator"
)

var (
	festivalsFieldNames          = builder.RawFieldNames(&Festivals{})
	festivalsRows                = strings.Join(festivalsFieldNames, ",")
	festivalsRowsExpectAutoSet   = strings.Join(stringx.Remove(festivalsFieldNames, "`festival_id`"), ",")
	festivalsRowsWithPlaceHolder = strings.Join(stringx.Remove(festivalsFieldNames, "`festival_id`"), "=?,") + "=?"
)

type (
	festivalsModel interface {
		Insert(ctx context.Context, data *Festivals) (sql.Result, error)

		// 自定义模版中扩展的方法 start ----->
		GetTableName() string
		Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error)
		InsertWithSession(ctx context.Context, session sqlx.Session, insertData map[string]interface{}) (sql.Result, error)
		DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error)
		UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error)
		SelectBuilder(fields ...string) squirrel.SelectBuilder
		CountBuilder(field ...string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error)
		FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error
		FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*Festivals, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*Festivals, error)
		FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*Festivals, *paginator.Pagination, error)
		// 自定义模版中扩展的方法 end ---->
		FindOne(ctx context.Context, festivalId uint64) (*Festivals, error)
		Update(ctx context.Context, data *Festivals) error
		Delete(ctx context.Context, festivalId uint64) error
	}

	defaultFestivalsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Festivals struct {
		FestivalId   uint64 `db:"festival_id"`   // 节日ID
		UserId       uint64 `db:"user_id"`       // 用户ID
		FestivalName string `db:"festival_name"` // 节日名称
		FestivalDate uint64 `db:"festival_date"` // 节日日期（YYYYMMDD格式）
		IsShowHome   int64  `db:"is_show_home"`  // 是否在首页显示 1-是 2-否
		CreatedAt    uint64 `db:"created_at"`    // 创建时间（秒级时间戳）
		UpdatedAt    uint64 `db:"updated_at"`    // 更新时间（秒级时间戳）
	}
)

func newFestivalsModel(conn sqlx.SqlConn) *defaultFestivalsModel {
	return &defaultFestivalsModel{
		conn:  conn,
		table: "`festivals`",
	}
}

func (m *defaultFestivalsModel) Delete(ctx context.Context, festivalId uint64) error {
	query := fmt.Sprintf("delete from %s where `festival_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, festivalId)
	return err
}

func (m *defaultFestivalsModel) FindOne(ctx context.Context, festivalId uint64) (*Festivals, error) {
	query := fmt.Sprintf("select %s from %s where `festival_id` = ? limit 1", festivalsRows, m.table)
	var resp Festivals
	err := m.conn.QueryRowCtx(ctx, &resp, query, festivalId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFestivalsModel) Insert(ctx context.Context, data *Festivals) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, festivalsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FestivalName, data.FestivalDate, data.IsShowHome, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

// 自定义模版中扩展的方法 start ----->

func (m *defaultFestivalsModel) GetTableName() string {
	return m.tableName()
}

func (m *defaultFestivalsModel) Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultFestivalsModel) ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error) {
	if session != nil {
		return session.ExecCtx(ctx, query, args...)
	}
	return m.conn.ExecCtx(ctx, query, args...)
}

func (m *defaultFestivalsModel) InsertWithSession(ctx context.Context, session sqlx.Session, insertData map[string]interface{}) (sql.Result, error) {
	insertBuilder := squirrel.Insert(m.table).SetMap(insertData)
	query, values, err := insertBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultFestivalsModel) DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error) {
	deleteBuilder := squirrel.Delete(m.table).Where(where)
	query, values, err := deleteBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultFestivalsModel) UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error) {
	updateBuilder := squirrel.Update(m.table).SetMap(updateData).Where(where)
	query, values, err := updateBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultFestivalsModel) SelectBuilder(fields ...string) squirrel.SelectBuilder {
	f := festivalsRows
	if len(fields) > 0 {
		f = strings.Join(fields, ",")
	}
	return squirrel.Select(f).From(m.table)
}

func (m *defaultFestivalsModel) CountBuilder(field ...string) squirrel.SelectBuilder {
	f := "*"
	if len(field) > 0 && field[0] != "" {
		f = field[0]
	}
	return squirrel.Select("COUNT(" + f + ")").From(m.table)
}

func (m *defaultFestivalsModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultFestivalsModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {
	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultFestivalsModel) FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error) {
	query, values, err := sumBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultFestivalsModel) FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return err
	}

	return m.conn.QueryRowsCtx(ctx, bindings, query, values...)

}

func (m *defaultFestivalsModel) FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*Festivals, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp Festivals

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}

}

func (m *defaultFestivalsModel) FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*Festivals, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Festivals

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFestivalsModel) FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*Festivals, *paginator.Pagination, error) {
	// 构建查询数据总条数的 sql 语句
	countQuery, countValues, err := paginator.CountDataSqlBuilder(rowBuilder).ToSql()
	if err != nil {
		return nil, nil, err
	}

	var total int64

	err = m.conn.QueryRowCtx(ctx, &total, countQuery, countValues...)

	if err != nil {
		return nil, nil, err
	}

	currentPage, limit, offset := paginator.PrepareOffsetLimit(page, perPage)
	pagination := paginator.NewPagination(total, currentPage, limit)

	builder := rowBuilder.Offset(uint64(offset)).Limit(uint64(limit))
	builder = paginator.WithOrderBy(orderBy, builder)

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, nil, err
	}

	var resp []*Festivals

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, pagination, nil
	default:
		return nil, nil, err
	}
}

// 自定义模版中扩展的方法 end ---->

func (m *defaultFestivalsModel) Update(ctx context.Context, data *Festivals) error {
	query := fmt.Sprintf("update %s set %s where `festival_id` = ?", m.table, festivalsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FestivalName, data.FestivalDate, data.IsShowHome, data.CreatedAt, data.UpdatedAt, data.FestivalId)
	return err
}

func (m *defaultFestivalsModel) tableName() string {
	return m.table
}
