// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/Masterminds/squirrel"
	"github.com/pudongping/momento-api/coreKit/paginator"
)

var (
	transactionsFieldNames          = builder.RawFieldNames(&Transactions{})
	transactionsRows                = strings.Join(transactionsFieldNames, ",")
	transactionsRowsExpectAutoSet   = strings.Join(stringx.Remove(transactionsFieldNames, "`transaction_id`"), ",")
	transactionsRowsWithPlaceHolder = strings.Join(stringx.Remove(transactionsFieldNames, "`transaction_id`"), "=?,") + "=?"
)

type (
	transactionsModel interface {
		Insert(ctx context.Context, data *Transactions) (sql.Result, error)

		// 自定义模版中扩展的方法 start ----->
		GetTableName() string
		Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error)
		DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error)
		UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error)
		SelectBuilder(fields ...string) squirrel.SelectBuilder
		CountBuilder(field ...string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error)
		FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error
		FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*Transactions, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*Transactions, error)
		FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*Transactions, *paginator.Pagination, error)
		// 自定义模版中扩展的方法 end ---->
		FindOne(ctx context.Context, transactionId uint64) (*Transactions, error)
		Update(ctx context.Context, data *Transactions) error
		Delete(ctx context.Context, transactionId uint64) error
	}

	defaultTransactionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Transactions struct {
		TransactionId   uint64  `db:"transaction_id"`    // 交易记录ID
		BookId          uint64  `db:"book_id"`           // 账本ID
		UserId          uint64  `db:"user_id"`           // 用户ID
		Type            string  `db:"type"`              // 交易类型
		Amount          float64 `db:"amount"`            // 金额
		TagId           uint64  `db:"tag_id"`            // 标签ID
		Remark          string  `db:"remark"`            // 备注
		TransactionTime uint64  `db:"transaction_time"`  // 交易时间（秒级时间戳）
		IsAutoGenerated int64   `db:"is_auto_generated"` // 是否自动生成 1-是 2-否
		CreatedAt       uint64  `db:"created_at"`        // 创建时间（秒级时间戳）
		UpdatedAt       uint64  `db:"updated_at"`        // 更新时间（秒级时间戳）
	}
)

func newTransactionsModel(conn sqlx.SqlConn) *defaultTransactionsModel {
	return &defaultTransactionsModel{
		conn:  conn,
		table: "`transactions`",
	}
}

func (m *defaultTransactionsModel) Delete(ctx context.Context, transactionId uint64) error {
	query := fmt.Sprintf("delete from %s where `transaction_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, transactionId)
	return err
}

func (m *defaultTransactionsModel) FindOne(ctx context.Context, transactionId uint64) (*Transactions, error) {
	query := fmt.Sprintf("select %s from %s where `transaction_id` = ? limit 1", transactionsRows, m.table)
	var resp Transactions
	err := m.conn.QueryRowCtx(ctx, &resp, query, transactionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransactionsModel) Insert(ctx context.Context, data *Transactions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, transactionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BookId, data.UserId, data.Type, data.Amount, data.TagId, data.Remark, data.TransactionTime, data.IsAutoGenerated, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

// 自定义模版中扩展的方法 start ----->

func (m *defaultTransactionsModel) GetTableName() string {
	return m.tableName()
}

func (m *defaultTransactionsModel) Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultTransactionsModel) ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error) {
	if session != nil {
		return session.ExecCtx(ctx, query, args...)
	}
	return m.conn.ExecCtx(ctx, query, args...)
}

func (m *defaultTransactionsModel) DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error) {
	deleteBuilder := squirrel.Delete(m.table).Where(where)
	query, values, err := deleteBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultTransactionsModel) UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error) {
	updateBuilder := squirrel.Update(m.table).SetMap(updateData).Where(where)
	query, values, err := updateBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultTransactionsModel) SelectBuilder(fields ...string) squirrel.SelectBuilder {
	f := transactionsRows
	if len(fields) > 0 {
		f = strings.Join(fields, ",")
	}
	return squirrel.Select(f).From(m.table)
}

func (m *defaultTransactionsModel) CountBuilder(field ...string) squirrel.SelectBuilder {
	f := "*"
	if len(field) > 0 && field[0] != "" {
		f = field[0]
	}
	return squirrel.Select("COUNT(" + f + ")").From(m.table)
}

func (m *defaultTransactionsModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultTransactionsModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {
	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultTransactionsModel) FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error) {
	query, values, err := sumBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultTransactionsModel) FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return err
	}

	return m.conn.QueryRowsCtx(ctx, bindings, query, values...)

}

func (m *defaultTransactionsModel) FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*Transactions, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp Transactions

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}

}

func (m *defaultTransactionsModel) FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*Transactions, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Transactions

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultTransactionsModel) FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*Transactions, *paginator.Pagination, error) {
	// 构建查询数据总条数的 sql 语句
	countQuery, countValues, err := paginator.CountDataSqlBuilder(rowBuilder).ToSql()
	if err != nil {
		return nil, nil, err
	}

	var total int64

	err = m.conn.QueryRowCtx(ctx, &total, countQuery, countValues...)

	if err != nil {
		return nil, nil, err
	}

	currentPage, limit, offset := paginator.PrepareOffsetLimit(page, perPage)
	pagination := paginator.NewPagination(total, currentPage, limit)

	builder := rowBuilder.Offset(uint64(offset)).Limit(uint64(limit))
	builder = paginator.WithOrderBy(orderBy, builder)

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, nil, err
	}

	var resp []*Transactions

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, pagination, nil
	default:
		return nil, nil, err
	}
}

// 自定义模版中扩展的方法 end ---->

func (m *defaultTransactionsModel) Update(ctx context.Context, data *Transactions) error {
	query := fmt.Sprintf("update %s set %s where `transaction_id` = ?", m.table, transactionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BookId, data.UserId, data.Type, data.Amount, data.TagId, data.Remark, data.TransactionTime, data.IsAutoGenerated, data.CreatedAt, data.UpdatedAt, data.TransactionId)
	return err
}

func (m *defaultTransactionsModel) tableName() string {
	return m.table
}
