// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/Masterminds/squirrel"
	"github.com/pudongping/momento-api/coreKit/paginator"
)

var (
	uploadFilesFieldNames          = builder.RawFieldNames(&UploadFiles{})
	uploadFilesRows                = strings.Join(uploadFilesFieldNames, ",")
	uploadFilesRowsExpectAutoSet   = strings.Join(stringx.Remove(uploadFilesFieldNames, "`file_id`"), ",")
	uploadFilesRowsWithPlaceHolder = strings.Join(stringx.Remove(uploadFilesFieldNames, "`file_id`"), "=?,") + "=?"
)

type (
	uploadFilesModel interface {
		Insert(ctx context.Context, data *UploadFiles) (sql.Result, error)

		// 自定义模版中扩展的方法 start ----->
		GetTableName() string
		Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error)
		InsertWithSession(ctx context.Context, session sqlx.Session, insertData map[string]interface{}) (sql.Result, error)
		DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error)
		UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error)
		SelectBuilder(fields ...string) squirrel.SelectBuilder
		CountBuilder(field ...string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error)
		FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error
		FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*UploadFiles, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*UploadFiles, error)
		FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*UploadFiles, *paginator.Pagination, error)
		// 自定义模版中扩展的方法 end ---->
		FindOne(ctx context.Context, fileId uint64) (*UploadFiles, error)
		Update(ctx context.Context, data *UploadFiles) error
		Delete(ctx context.Context, fileId uint64) error
	}

	defaultUploadFilesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UploadFiles struct {
		FileId       uint64 `db:"file_id"`       // 文件ID
		UserId       uint64 `db:"user_id"`       // 用户ID
		RelativePath string `db:"relative_path"` // 文件相对路径
		AbsoluteUrl  string `db:"absolute_url"`  // 文件绝对URL
		FileSize     uint64 `db:"file_size"`     // 文件大小（字节）
		FileType     string `db:"file_type"`     // 文件类型
		BusinessType string `db:"business_type"` // 业务类型
		UploadTime   uint64 `db:"upload_time"`   // 上传时间（秒级时间戳）
		CreatedAt    uint64 `db:"created_at"`    // 创建时间（秒级时间戳）
	}
)

func newUploadFilesModel(conn sqlx.SqlConn) *defaultUploadFilesModel {
	return &defaultUploadFilesModel{
		conn:  conn,
		table: "`upload_files`",
	}
}

func (m *defaultUploadFilesModel) Delete(ctx context.Context, fileId uint64) error {
	query := fmt.Sprintf("delete from %s where `file_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, fileId)
	return err
}

func (m *defaultUploadFilesModel) FindOne(ctx context.Context, fileId uint64) (*UploadFiles, error) {
	query := fmt.Sprintf("select %s from %s where `file_id` = ? limit 1", uploadFilesRows, m.table)
	var resp UploadFiles
	err := m.conn.QueryRowCtx(ctx, &resp, query, fileId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUploadFilesModel) Insert(ctx context.Context, data *UploadFiles) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, uploadFilesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.RelativePath, data.AbsoluteUrl, data.FileSize, data.FileType, data.BusinessType, data.UploadTime, data.CreatedAt)
	return ret, err
}

// 自定义模版中扩展的方法 start ----->

func (m *defaultUploadFilesModel) GetTableName() string {
	return m.tableName()
}

func (m *defaultUploadFilesModel) Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultUploadFilesModel) ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error) {
	if session != nil {
		return session.ExecCtx(ctx, query, args...)
	}
	return m.conn.ExecCtx(ctx, query, args...)
}

func (m *defaultUploadFilesModel) InsertWithSession(ctx context.Context, session sqlx.Session, insertData map[string]interface{}) (sql.Result, error) {
	insertBuilder := squirrel.Insert(m.table).SetMap(insertData)
	query, values, err := insertBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultUploadFilesModel) DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error) {
	deleteBuilder := squirrel.Delete(m.table).Where(where)
	query, values, err := deleteBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultUploadFilesModel) UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error) {
	updateBuilder := squirrel.Update(m.table).SetMap(updateData).Where(where)
	query, values, err := updateBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultUploadFilesModel) SelectBuilder(fields ...string) squirrel.SelectBuilder {
	f := uploadFilesRows
	if len(fields) > 0 {
		f = strings.Join(fields, ",")
	}
	return squirrel.Select(f).From(m.table)
}

func (m *defaultUploadFilesModel) CountBuilder(field ...string) squirrel.SelectBuilder {
	f := "*"
	if len(field) > 0 && field[0] != "" {
		f = field[0]
	}
	return squirrel.Select("COUNT(" + f + ")").From(m.table)
}

func (m *defaultUploadFilesModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultUploadFilesModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {
	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUploadFilesModel) FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error) {
	query, values, err := sumBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUploadFilesModel) FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return err
	}

	return m.conn.QueryRowsCtx(ctx, bindings, query, values...)

}

func (m *defaultUploadFilesModel) FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*UploadFiles, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp UploadFiles

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}

}

func (m *defaultUploadFilesModel) FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*UploadFiles, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UploadFiles

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUploadFilesModel) FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*UploadFiles, *paginator.Pagination, error) {
	// 构建查询数据总条数的 sql 语句
	countQuery, countValues, err := paginator.CountDataSqlBuilder(rowBuilder).ToSql()
	if err != nil {
		return nil, nil, err
	}

	var total int64

	err = m.conn.QueryRowCtx(ctx, &total, countQuery, countValues...)

	if err != nil {
		return nil, nil, err
	}

	currentPage, limit, offset := paginator.PrepareOffsetLimit(page, perPage)
	pagination := paginator.NewPagination(total, currentPage, limit)

	builder := rowBuilder.Offset(uint64(offset)).Limit(uint64(limit))
	builder = paginator.WithOrderBy(orderBy, builder)

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, nil, err
	}

	var resp []*UploadFiles

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, pagination, nil
	default:
		return nil, nil, err
	}
}

// 自定义模版中扩展的方法 end ---->

func (m *defaultUploadFilesModel) Update(ctx context.Context, data *UploadFiles) error {
	query := fmt.Sprintf("update %s set %s where `file_id` = ?", m.table, uploadFilesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.RelativePath, data.AbsoluteUrl, data.FileSize, data.FileType, data.BusinessType, data.UploadTime, data.CreatedAt, data.FileId)
	return err
}

func (m *defaultUploadFilesModel) tableName() string {
	return m.table
}
