// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/Masterminds/squirrel"
	"github.com/pudongping/momento-api/coreKit/paginator"
)

var (
	usersFieldNames          = builder.RawFieldNames(&Users{})
	usersRows                = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet   = strings.Join(stringx.Remove(usersFieldNames), ",")
	usersRowsWithPlaceHolder = strings.Join(stringx.Remove(usersFieldNames, "`user_id`"), "=?,") + "=?"
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *Users) (sql.Result, error)

		// 自定义模版中扩展的方法 start ----->
		GetTableName() string
		Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error)
		DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error)
		UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error)
		SelectBuilder(fields ...string) squirrel.SelectBuilder
		CountBuilder(field ...string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error)
		FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error
		FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*Users, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*Users, error)
		FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*Users, *paginator.Pagination, error)
		// 自定义模版中扩展的方法 end ---->
		FindOne(ctx context.Context, userId uint64) (*Users, error)
		FindOneByOpenid(ctx context.Context, openid string) (*Users, error)
		Update(ctx context.Context, data *Users) error
		Delete(ctx context.Context, userId uint64) error
	}

	defaultUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Users struct {
		UserId        uint64 `db:"user_id"`         // 用户唯一ID（雪花算法）
		Openid        string `db:"openid"`          // 微信openid
		Unionid       string `db:"unionid"`         // 微信unionid
		Nickname      string `db:"nickname"`        // 用户昵称
		Avatar        string `db:"avatar"`          // 用户头像URL
		Phone         string `db:"phone"`           // 手机号
		IsDisable     int64  `db:"is_disable"`      // 是否禁用 1-启用 2-禁用
		RegisterIp    string `db:"register_ip"`     // 注册时的ip
		LoginIp       string `db:"login_ip"`        // 登录时的ip
		LastLoginTime uint64 `db:"last_login_time"` // 最近登录的时间（秒级时间戳）
		CreatedAt     uint64 `db:"created_at"`      // 创建时间（秒级时间戳）
		UpdatedAt     uint64 `db:"updated_at"`      // 更新时间（秒级时间戳）
	}
)

func newUsersModel(conn sqlx.SqlConn) *defaultUsersModel {
	return &defaultUsersModel{
		conn:  conn,
		table: "`users`",
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, userId uint64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, userId uint64) (*Users, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", usersRows, m.table)
	var resp Users
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByOpenid(ctx context.Context, openid string) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where `openid` = ? limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, openid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, usersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Openid, data.Unionid, data.Nickname, data.Avatar, data.Phone, data.IsDisable, data.RegisterIp, data.LoginIp, data.LastLoginTime, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

// 自定义模版中扩展的方法 start ----->

func (m *defaultUsersModel) GetTableName() string {
	return m.tableName()
}

func (m *defaultUsersModel) Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultUsersModel) ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error) {
	if session != nil {
		return session.ExecCtx(ctx, query, args...)
	}
	return m.conn.ExecCtx(ctx, query, args...)
}

func (m *defaultUsersModel) DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error) {
	deleteBuilder := squirrel.Delete(m.table).Where(where)
	query, values, err := deleteBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultUsersModel) UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error) {
	updateBuilder := squirrel.Update(m.table).SetMap(updateData).Where(where)
	query, values, err := updateBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultUsersModel) SelectBuilder(fields ...string) squirrel.SelectBuilder {
	f := usersRows
	if len(fields) > 0 {
		f = strings.Join(fields, ",")
	}
	return squirrel.Select(f).From(m.table)
}

func (m *defaultUsersModel) CountBuilder(field ...string) squirrel.SelectBuilder {
	f := "*"
	if len(field) > 0 && field[0] != "" {
		f = field[0]
	}
	return squirrel.Select("COUNT(" + f + ")").From(m.table)
}

func (m *defaultUsersModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultUsersModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {
	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUsersModel) FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error) {
	query, values, err := sumBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUsersModel) FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return err
	}

	return m.conn.QueryRowsCtx(ctx, bindings, query, values...)

}

func (m *defaultUsersModel) FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*Users, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp Users

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}

}

func (m *defaultUsersModel) FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*Users, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Users

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*Users, *paginator.Pagination, error) {
	// 构建查询数据总条数的 sql 语句
	countQuery, countValues, err := paginator.CountDataSqlBuilder(rowBuilder).ToSql()
	if err != nil {
		return nil, nil, err
	}

	var total int64

	err = m.conn.QueryRowCtx(ctx, &total, countQuery, countValues...)

	if err != nil {
		return nil, nil, err
	}

	currentPage, limit, offset := paginator.PrepareOffsetLimit(page, perPage)
	pagination := paginator.NewPagination(total, currentPage, limit)

	builder := rowBuilder.Offset(uint64(offset)).Limit(uint64(limit))
	builder = paginator.WithOrderBy(orderBy, builder)

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, nil, err
	}

	var resp []*Users

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, pagination, nil
	default:
		return nil, nil, err
	}
}

// 自定义模版中扩展的方法 end ---->

func (m *defaultUsersModel) Update(ctx context.Context, newData *Users) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, usersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Openid, newData.Unionid, newData.Nickname, newData.Avatar, newData.Phone, newData.IsDisable, newData.RegisterIp, newData.LoginIp, newData.LastLoginTime, newData.CreatedAt, newData.UpdatedAt, newData.UserId)
	return err
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}
