// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/Masterminds/squirrel"
	"github.com/pudongping/momento-api/coreKit/paginator"
)

var (
	userSettingsFieldNames          = builder.RawFieldNames(&UserSettings{})
	userSettingsRows                = strings.Join(userSettingsFieldNames, ",")
	userSettingsRowsExpectAutoSet   = strings.Join(stringx.Remove(userSettingsFieldNames, "`user_setting_id`"), ",")
	userSettingsRowsWithPlaceHolder = strings.Join(stringx.Remove(userSettingsFieldNames, "`user_setting_id`"), "=?,") + "=?"
)

type (
	userSettingsModel interface {
		Insert(ctx context.Context, data *UserSettings) (sql.Result, error)

		// 自定义模版中扩展的方法 start ----->
		GetTableName() string
		Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error)
		InsertWithSession(ctx context.Context, session sqlx.Session, insertData map[string]interface{}) (sql.Result, error)
		DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error)
		UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error)
		SelectBuilder(fields ...string) squirrel.SelectBuilder
		CountBuilder(field ...string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error)
		FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error
		FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*UserSettings, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*UserSettings, error)
		FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*UserSettings, *paginator.Pagination, error)
		// 自定义模版中扩展的方法 end ---->
		FindOne(ctx context.Context, userSettingId uint64) (*UserSettings, error)
		FindOneByUserId(ctx context.Context, userId uint64) (*UserSettings, error)
		Update(ctx context.Context, data *UserSettings) error
		Delete(ctx context.Context, userSettingId uint64) error
	}

	defaultUserSettingsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserSettings struct {
		UserSettingId uint64  `db:"user_setting_id"` // 主键ID
		UserId        uint64  `db:"user_id"`         // 用户ID
		BackgroundUrl string  `db:"background_url"`  // 首页背景图片URL
		Budget        float64 `db:"budget"`          // 月度预算
		CreatedAt     uint64  `db:"created_at"`      // 创建时间（秒级时间戳）
		UpdatedAt     uint64  `db:"updated_at"`      // 更新时间（秒级时间戳）
	}
)

func newUserSettingsModel(conn sqlx.SqlConn) *defaultUserSettingsModel {
	return &defaultUserSettingsModel{
		conn:  conn,
		table: "`user_settings`",
	}
}

func (m *defaultUserSettingsModel) Delete(ctx context.Context, userSettingId uint64) error {
	query := fmt.Sprintf("delete from %s where `user_setting_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userSettingId)
	return err
}

func (m *defaultUserSettingsModel) FindOne(ctx context.Context, userSettingId uint64) (*UserSettings, error) {
	query := fmt.Sprintf("select %s from %s where `user_setting_id` = ? limit 1", userSettingsRows, m.table)
	var resp UserSettings
	err := m.conn.QueryRowCtx(ctx, &resp, query, userSettingId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSettingsModel) FindOneByUserId(ctx context.Context, userId uint64) (*UserSettings, error) {
	var resp UserSettings
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userSettingsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSettingsModel) Insert(ctx context.Context, data *UserSettings) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userSettingsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.BackgroundUrl, data.Budget, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

// 自定义模版中扩展的方法 start ----->

func (m *defaultUserSettingsModel) GetTableName() string {
	return m.tableName()
}

func (m *defaultUserSettingsModel) Transaction(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultUserSettingsModel) ExecContext(ctx context.Context, session sqlx.Session, query string, args ...interface{}) (sql.Result, error) {
	if session != nil {
		return session.ExecCtx(ctx, query, args...)
	}
	return m.conn.ExecCtx(ctx, query, args...)
}

func (m *defaultUserSettingsModel) InsertWithSession(ctx context.Context, session sqlx.Session, insertData map[string]interface{}) (sql.Result, error) {
	insertBuilder := squirrel.Insert(m.table).SetMap(insertData)
	query, values, err := insertBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultUserSettingsModel) DeleteFilter(ctx context.Context, session sqlx.Session, where squirrel.Sqlizer) (sql.Result, error) {
	deleteBuilder := squirrel.Delete(m.table).Where(where)
	query, values, err := deleteBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultUserSettingsModel) UpdateFilter(ctx context.Context, session sqlx.Session, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error) {
	updateBuilder := squirrel.Update(m.table).SetMap(updateData).Where(where)
	query, values, err := updateBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	return m.ExecContext(ctx, session, query, values...)
}

func (m *defaultUserSettingsModel) SelectBuilder(fields ...string) squirrel.SelectBuilder {
	f := userSettingsRows
	if len(fields) > 0 {
		f = strings.Join(fields, ",")
	}
	return squirrel.Select(f).From(m.table)
}

func (m *defaultUserSettingsModel) CountBuilder(field ...string) squirrel.SelectBuilder {
	f := "*"
	if len(field) > 0 && field[0] != "" {
		f = field[0]
	}
	return squirrel.Select("COUNT(" + f + ")").From(m.table)
}

func (m *defaultUserSettingsModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultUserSettingsModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {
	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserSettingsModel) FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder) (float64, error) {
	query, values, err := sumBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserSettingsModel) FindAny(ctx context.Context, rowBuilder squirrel.SelectBuilder, bindings interface{}) error {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return err
	}

	return m.conn.QueryRowsCtx(ctx, bindings, query, values...)

}

func (m *defaultUserSettingsModel) FindOneByQuery(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*UserSettings, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp UserSettings

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return &resp, nil
	default:
		return nil, err
	}

}

func (m *defaultUserSettingsModel) FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*UserSettings, error) {
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserSettings

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserSettingsModel) FindListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, perPage int64, orderBy string) ([]*UserSettings, *paginator.Pagination, error) {
	// 构建查询数据总条数的 sql 语句
	countQuery, countValues, err := paginator.CountDataSqlBuilder(rowBuilder).ToSql()
	if err != nil {
		return nil, nil, err
	}

	var total int64

	err = m.conn.QueryRowCtx(ctx, &total, countQuery, countValues...)

	if err != nil {
		return nil, nil, err
	}

	currentPage, limit, offset := paginator.PrepareOffsetLimit(page, perPage)
	pagination := paginator.NewPagination(total, currentPage, limit)

	builder := rowBuilder.Offset(uint64(offset)).Limit(uint64(limit))
	builder = paginator.WithOrderBy(orderBy, builder)

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, nil, err
	}

	var resp []*UserSettings

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, pagination, nil
	default:
		return nil, nil, err
	}
}

// 自定义模版中扩展的方法 end ---->

func (m *defaultUserSettingsModel) Update(ctx context.Context, newData *UserSettings) error {
	query := fmt.Sprintf("update %s set %s where `user_setting_id` = ?", m.table, userSettingsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.BackgroundUrl, newData.Budget, newData.CreatedAt, newData.UpdatedAt, newData.UserSettingId)
	return err
}

func (m *defaultUserSettingsModel) tableName() string {
	return m.table
}
