package model

import "github.com/zeromicro/go-zero/core/stores/sqlx"

var ErrNotFound = sqlx.ErrNotFound

// users 表相关
const (
	UserIsDisableYes = 1 // 启用
	UserIsDisableNo  = 2 // 禁用
)

// tags 表相关
const (
	TagsIsSystemYes = 1 // 系统标签
	TagsIsSystemNo  = 2 // 用户自定义标签

	// type
	TagsTypeExpense = "expense" // 支出
	TagsTypeIncome  = "income"  // 收入
)

// festivals 表相关
const (
	// is_show_home 是否显示在首页
	FestivalIsShowHomeYes = 1 // 显示
	FestivalIsShowHomeNo  = 2 // 不显示
)

// account_book_members 表相关
const (
	// is_creator 是否创建者
	AccountBookMemberIsCreatorYes = 1 // 是
	AccountBookMemberIsCreatorNo  = 2 // 否

	// is_default 是否为默认账本
	AccountBookMemberIsDefaultYes = 1 // 是
	AccountBookMemberIsDefaultNo  = 2 // 否

	// status 成员状态
	AccountBookMemberStatusJoined   = "joined"   // 已加入
	AccountBookMemberStatusWaiting  = "waiting"  // 待加入
	AccountBookMemberStatusRejected = "rejected" // 已拒绝
)

// account_book_invitations 表相关
const (
	// status 邀请状态
	AccountBookInvitationStatusPending  = "pending"  // 待处理
	AccountBookInvitationStatusAccepted = "accepted" // 已接受
	AccountBookInvitationStatusRejected = "rejected" // 已拒绝
)

// transactions 表相关
const (
	// type 交易类型
	TransactionTypeExpense = "expense" // 支出
	TransactionTypeIncome  = "income"  // 收入

	// is_auto_generated 是否自动生成
	TransactionIsAutoGeneratedYes = 1 // 是
	TransactionIsAutoGeneratedNo  = 2 // 否
)

// recurring_transactions 表相关
const (
	// type 交易类型
	RecurringTransactionTypeExpense = "expense" // 支出
	RecurringTransactionTypeIncome  = "income"  // 收入

	// recurring_type 周期类型
	RecurringTransactionTypeDaily     = "daily"     // 每日
	RecurringTransactionTypeWeekly    = "weekly"    // 每周
	RecurringTransactionTypeMonthly   = "monthly"   // 每月
	RecurringTransactionTypeQuarterly = "quarterly" // 每季度
	RecurringTransactionTypeYearly    = "yearly"    // 每年

	// is_recurring_enabled 是否启用
	RecurringTransactionIsEnabledYes = 1 // 是
	RecurringTransactionIsEnabledNo  = 2 // 否
)
