// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	festival "github.com/pudongping/momento-api/internal/handler/festival"
	tag "github.com/pudongping/momento-api/internal/handler/tag"
	transaction "github.com/pudongping/momento-api/internal/handler/transaction"
	user "github.com/pudongping/momento-api/internal/handler/user"
	"github.com/pudongping/momento-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthCheckMiddleware},
			[]rest.Route{
				{
					// 添加节日
					Method:  http.MethodPost,
					Path:    "/festivals/add",
					Handler: festival.FestivalAddHandler(serverCtx),
				},
				{
					// 删除节日
					Method:  http.MethodDelete,
					Path:    "/festivals/delete",
					Handler: festival.FestivalDeleteHandler(serverCtx),
				},
				{
					// 获取节日列表
					Method:  http.MethodGet,
					Path:    "/festivals/list",
					Handler: festival.FestivalListHandler(serverCtx),
				},
				{
					// 切换节日显示状态
					Method:  http.MethodPut,
					Path:    "/festivals/toggle",
					Handler: festival.FestivalToggleHandler(serverCtx),
				},
				{
					// 更新节日
					Method:  http.MethodPut,
					Path:    "/festivals/update",
					Handler: festival.FestivalUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthCheckMiddleware},
			[]rest.Route{
				{
					// 添加自定义标签
					Method:  http.MethodPost,
					Path:    "/tags/add",
					Handler: tag.TagAddHandler(serverCtx),
				},
				{
					// 删除标签
					Method:  http.MethodDelete,
					Path:    "/tags/delete",
					Handler: tag.TagDeleteHandler(serverCtx),
				},
				{
					// 获取标签列表
					Method:  http.MethodGet,
					Path:    "/tags/list",
					Handler: tag.TagListHandler(serverCtx),
				},
				{
					// 更新自定义标签
					Method:  http.MethodPut,
					Path:    "/tags/update",
					Handler: tag.TagUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthCheckMiddleware},
			[]rest.Route{
				{
					// 获取交易流水列表
					Method:  http.MethodGet,
					Path:    "/transactions/list",
					Handler: transaction.TransactionListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 小程序授权登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthCheckMiddleware},
			[]rest.Route{
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: user.UserInfoHandler(serverCtx),
				},
				{
					// 用户退出登录
					Method:  http.MethodPost,
					Path:    "/user/logout",
					Handler: user.UserLogoutHandler(serverCtx),
				},
				{
					// 获取用户设置
					Method:  http.MethodGet,
					Path:    "/user/settings",
					Handler: user.UserSettingsHandler(serverCtx),
				},
				{
					// 更新用户设置
					Method:  http.MethodPut,
					Path:    "/user/settings",
					Handler: user.UpdateUserSettingsHandler(serverCtx),
				},
				{
					// 更新用户信息
					Method:  http.MethodPut,
					Path:    "/user/update",
					Handler: user.UserUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
	)
}
